# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-05 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the task', max_length=200)),
                ('time', models.IntegerField(help_text='Time in minutes for the task')),
            ],
        ),
    ]
