# Generated by Django 2.0.2 on 2018-03-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_hour_ratio', models.DecimalField(decimal_places=2, default=2, help_text='Number of points earned by one hour of work', max_digits=6)),
                ('daily_high_score', models.DecimalField(decimal_places=2, default=0, help_text='Most points accumulated in a day', max_digits=6)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, help_text='Total points accumulated', max_digits=6)),
            ],
        ),
    ]
