# Generated by Django 2.0.2 on 2018-03-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='name',
            field=models.CharField(default='  ', help_text='Nickname for this set of settings', max_length=200),
            preserve_default=False,
        ),
    ]
